//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mqttservice
{
    using System;
    using System.Collections.Generic;
    
    public partial class sensor
    {
        public int Id { get; set; }
        public string SensorType { get; set; }
        public string SensorData { get; set; }
        public string DateCreated { get; set; }
    }
}
